# Use postgres/example user/password credentials
version: '3'

services:
  goose-auth-api:
    image: gudrb963/goose-auth-api:latest
    container_name: goose-auth-api
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gooseauth
      - SPRING_DATASOURCE_USERNAME=gooseauth
      - SPRING_DATASOURCE_PASSWORD=gooseauth
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  postgres:
    image: postgres:13
    container_name: goose-auth-api-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gooseauth
      POSTGRES_PASSWORD: gooseauth
      POSTGRES_DB: gooseauth
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gooseauth"]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: goose-auth-api-redis
    ports:
      - 6379:6379
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  postgres-db-volume: