spring:
  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: i18n/exception

social:
  kakao:
    kauth:
      url: https://kauth.kakao.com
    kapi:
      url: https://kapi.kakao.com

    redirect: /social/login/kakao
    clientId: vault
