logging:
  level:
    root: warn
    me:
      synology:
        gooseauthapiserver: debug

spring:
  datasource:
    username: docker-compose-environment
    password: docker-compose-environment
    url: docker-compose-environment

  redis:
    host: vault
    port: 6379
    timeout: 3000

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auth: update
        default_batch_fetch_size: 1000
        format_sql: true

info:
  api:
    id: API-SERVER
    url: http://localhost:8080
