logging:
  level:
    root: warn
    me:
      synology:
        gooseauthapiserver: debug

spring:
  datasource:
    username: vault
    password: vault
    url: vault

  config:
    import: vault://

  cloud:
    vault:
      uri: http://localhost:8200
      token: insert-your-TOKEN

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auth: vault
        default_batch_fetch_size: 1000
        format_sql: true

info:
  api:
    id: 500
    url: http://localhost:8080
