server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

info:
  api:
    id: 500
