server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: i18n/exception

info:
  api:
    id: 500
    url: https://goose-auth.synology.me
